services:
  postgres:
    container_name: TMS_Test
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tms_test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: TMS_Redis
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pg_data:
